Move document ready handlers to bottom. Fixes bug when zoomooz is loaded with a script loader. Document might be already ready when $(document).ready(...) is called which causes errors like
TypeError: Object #<Object> has no method 'zoomContainer'

Because it gets called before the actual function is created.